"""baseline

Revision ID: 0af431c27790
Revises: 
Create Date: 2026-08-09 11:43:19.949257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af431c27790'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_clips_owner_id'), 'clips', ['owner_id'], unique=False)
    op.add_column('flows', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_flows_owner_id'), 'flows', ['owner_id'], unique=False)
    op.add_column('sections', sa.Column('owner_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sections_owner_id'), 'sections', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_owner_id'), table_name='sections')
    op.drop_column('sections', 'owner_id')
    op.drop_index(op.f('ix_flows_owner_id'), table_name='flows')
    op.drop_column('flows', 'owner_id')
    op.drop_index(op.f('ix_clips_owner_id'), table_name='clips')
    op.drop_column('clips', 'owner_id')
    # ### end Alembic commands ###
